### ISSUE TITLE
Update license footer to use Creative Commons [Epic]

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/horusec-docs#96]
The goal of this epic is to make sure that all documentation footer uses `Creative Commons` license instead of `All Rights Reserved`:

## Task

- [x] [Horussec](https://github.com/ZupIT/docs-horusec/issues/95)
- [x] [ritchie](https://github.com/ZupIT/docs-ritchie/issues/129)
- [x] [charles](https://github.com/ZupIT/charlescd-docs/issues/9)
- [ ] [beagle](https://github.com/ZupIT/beagle-docs/issues/719)
